redactions = [ "*_SECRET", "*_KEY", "*_PASSWORD" ]

# Many tools are set to "latest" to take advantage of idiomatic version files, which will automatically update the tool to the latest version when the version file is updated. This allows us to keep our tools up to date without having to manually update the version in this configuration file.
[tools]
"aqua:vercel-labs/agent-browser" = "0.31.1"
bun                              = "latest"
just                             = "latest"
markdownlint-cli2                = "0.22.1"
oxfmt                            = "latest"
oxlint                           = "latest"
"pipx:mdformat"                  = { version = "1.0.0", uvx_args = "--with mdformat-gfm --with mdformat-admon --with mdformat-config --with mdformat-footnote --with mdformat-simple-breaks --with mdformat-web --with mdformat-ruff --with mdformat-gfm-alerts --with mdformat-toc --with mdformat-front-matters" }
"pipx:pre-commit"                = "4.6.0"
shellcheck = "0.11.0"
syft                             = "latest"
taplo                            = "latest"

# Many of these settings are defaults, but we are explicit in case they change in the future and to make it clear to users what is enabled.
[settings]
activate_aggressive                 = true
env_cache                           = true
exec_auto_install                   = true
github_attestations                 = true
idiomatic_version_file_enable_tools = [ "bun", "python" ]
lockfile                            = true
pin                                 = true
slsa                                = true

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true

[env]
ECC_DISABLED_HOOKS = "pre:bash:gateguard-fact-force,pre:edit-write:gateguard-fact-force"
ECC_GATEGUARD      = "off"
_.file             = [ '.env', ".env.local" ]
